import pytest
from user import User

def test_user_creation(): #test that user creation works correctly
    user1 = User("lindelani", "lindelani.nethamba@gmail.com")
    assert user1.username == "lindelani"
    assert user1.email_address == "lindelani.nethamba@gmail.com"

def test_autoset_user_id(): #test that user_id is autogenerated
    user1 = User("lindelani", "lindelani.nethamba@gmail.com")
    assert user1.user_id is None

def test_is_active_default(): #test that is active is default set to True
    user1 = User("lindelani", "lindelani.nethamba@gmail.com")
    assert user1.is_active == True

def test_is_active_false(): #test that user is_active can be set to false correctly
    user1 = User("lindelani", "lindelani.nethamba@gmail.com", is_active=False)
    assert user1.is_active == False

